import json
import os
import matplotlib.pyplot as plt
import warnings
from matplotlib.transforms import Affine2D
import numpy as np

def read_json(dir,dataset):
    # reads a json file generated by lm-eval and returns relevant data
    try:
        with open(dir, 'r') as file:
            data=json.load(file)
    except Exception as e:
        warnings.warn(f"Got error trying to open {dir}: {e}.")
        return False
    # check if the fine-tuning dataset of interest was evaluated in this file
    try:
        if dataset not in data['configs'].keys():
            return False
    except KeyError as e:
        warnings.warn(f"Got key error for {dir}: {e}")
        return False
    model_args=data['config']['model_args']
    try:
        base_model=model_args.split(',')[0].split('=')[1]
    except Exception as e:
        try:
            base_model=data['config']['model_args']['pretrained']
        except:
            print(f"Error in file {dir}")
            raise(e)
    # determine the pretraining dataset and base model
    # base model is an int denoting the time step of the base model
    if "cos_" in base_model:
        base_model = 10 if '10' in base_model else int(base_model[-1])
        pdset="Cosmopedia"
    elif "merged" in base_model:
        base_model = 10 if '10' in base_model else int(base_model[-1])
        pdset="Fineweb"
    elif "qwen_temporal_evals" in base_model:
        base_model = 10 if '10' in base_model else int(base_model[-1])
        pdset="Fineweb"
    elif "mistralai/mistral-7b-v0.1" in base_model.lower():
        base_model=0
        pdset=""
    elif base_model=="qwen0":
        base_model=0
        pdset=""
    elif "qwen" in base_model:
        base_model=int(base_model[-1])
        pdset="Fineweb"
    else:
        print(f"pretrain dataset not found for {base_model}.")
    # determine which fine-tuning patch, if any, was used during the evaluation
    try:
        if "peft" in model_args:
            peft=model_args.split("peft=")[1]
        else:
            peft="No Patch"
    except:
        if "peft" in model_args.keys():
            peft=model_args['peft']
        else:
            peft="No Patch"
    return base_model, peft, pdset, data

def get_files(start_dir):
    # iterates through all files in a given start directory and returns a list of relevant files that should be used for plotting
    contents = os.listdir(start_dir)
    contents = [f"{start_dir}/{c}" for c in contents]
    files=[]
    while len(contents)>0:
        content=contents[0]
        if os.path.isdir(content):
            for c in os.listdir(content):
                contents.append(f"{content}/{c}")
        else:
            files.append(content)
        contents.remove(content)
    return files

METRIC_NAMES={'winogrande':'acc,none',
              'boolq':'acc,none',
              'humaneval':'pass@1,create_test',
              'gsm8k':'exact_match,flexible-extract',
              'arc_easy':'acc,none',
              'arc_challenge':'acc,none',
              'mnli':'acc,none',
              'sst2':'acc,none'}

def plot_scores_avg(benchmark, pt_set, base_perf_path, portllm_perf_path, recurrent_ft_perf_path,rep,postfix="",gen_legend=False, add_arrow=True):
    # rep should be list of ints specifying the repetitions, e.g., [1,2,3]
    # base_perf_path, portllm_perf_path, and recurrent_ft_perf_path should be lists of folder dirs corresponding to rep
    if base_perf_path is not None:
        b_scores_arr=None
        for i,folder in enumerate(base_perf_path):
            base_dirs=get_files(folder)
            base_idx_i,base_scores_i = [],[]
            for dir in base_dirs:
                if not read_json(dir,benchmark):
                    continue
                base_model,peft,pdset,data=read_json(dir,benchmark)
                if not peft == "No Patch":
                    warnings.warn(f"Found json that used peft {peft} in base_perf_path in {dir}.")
                    continue # should not include score that used a patch in base model scores
                base_idx_i.append(base_model)
                base_scores_i.append(data['results'][benchmark][METRIC_NAMES[benchmark]])
            idxs=sorted(range(len(base_idx_i)),key=lambda x: base_idx_i[x]) # sort according to ascending time steps
            base_idx_i=[base_idx_i[i] for i in idxs]
            base_scores_i=[base_scores_i[i] for i in idxs]
            if b_scores_arr is None:
                b_scores_arr=np.zeros((len(base_idx_i),len(rep)))
            try:
                b_scores_arr[:,i]=np.array(base_scores_i)
            except Exception as e:
                print(f"Found error with file {dir}.")
                print(b_scores_arr)
                print(base_scores_i)
                print(base_idx_i)
                raise(e)
        base_scores=np.mean(b_scores_arr,axis=1)
        base_95ci=1.96*np.std(b_scores_arr,axis=1)/np.sqrt(len(rep))
        base_idx=np.array(base_idx_i)
    if portllm_perf_path is not None:
        p_scores_arr=None
        for i,folder in enumerate(portllm_perf_path):
            pllm_dirs=get_files(folder)
            pllm_idx_i,pllm_scores_i = [],[]
            for dir in pllm_dirs:
                if not read_json(dir,benchmark):
                    continue
                base_model,peft,pdset,data=read_json(dir,benchmark)
                if peft == "No Patch":
                    warnings.warn(f"Found json that does not use peft in portllm_perf_path in {dir}.")
                    continue # all PortLLM scores should be obtained using a patch
                pllm_idx_i.append(base_model)
                pllm_scores_i.append(data['results'][benchmark][METRIC_NAMES[benchmark]])
            idxs=sorted(range(len(pllm_idx_i)),key=lambda x: pllm_idx_i[x])
            pllm_idx_i=[pllm_idx_i[i] for i in idxs]
            pllm_scores_i=[pllm_scores_i[i] for i in idxs]
            if p_scores_arr is None:
                p_scores_arr=np.zeros((len(pllm_idx_i),len(rep)))
            p_scores_arr[:,i]=np.array(pllm_scores_i)
        pllm_scores=np.mean(p_scores_arr,axis=1)
        pllm_95ci=1.96*np.std(p_scores_arr,axis=1)/np.sqrt(len(rep))
        pllm_idx=np.array(pllm_idx_i)
    if recurrent_ft_perf_path is not None:
        r_scores_arr=None
        for i,folder in enumerate(recurrent_ft_perf_path):
            r_dirs=get_files(folder)
            r_idx_i,r_scores_i = [],[]
            for dir in r_dirs:
                if not read_json(dir,benchmark):
                    continue
                base_model,peft,pdset,data=read_json(dir,benchmark)
                if peft == "No Patch":
                    warnings.warn(f"Found json that used no peft in recurrent_ft_perf_path in {dir}.")
                    continue
                r_idx_i.append(base_model)
                r_scores_i.append(data['results'][benchmark][METRIC_NAMES[benchmark]])
            idxs=sorted(range(len(r_idx_i)),key=lambda x: r_idx_i[x])
            r_idx_i=[r_idx_i[i] for i in idxs]
            r_scores_i=[r_scores_i[i] for i in idxs]
            if r_scores_arr is None:
                r_scores_arr=np.zeros((len(r_idx_i),len(rep)))
            try:
                r_scores_arr[:,i]=np.array(r_scores_i)
            except Exception as e:
                print("Found error with files.")
                print(r_scores_arr)
                print(r_scores_i)
                raise(e)
        re_scores=np.mean(r_scores_arr,axis=1)
        re_95ci=1.96*np.std(r_scores_arr,axis=1)/np.sqrt(len(rep))
        re_idx=np.array(r_idx_i)
    if recurrent_ft_perf_path and portllm_perf_path:
        if not 0 in re_idx: # stepwise/recurrent ft are the same as portllm at t=0, files only saved in portllm folder
            re_idx=np.insert(re_idx,0,pllm_idx[0])
            re_scores=np.insert(re_scores,0,pllm_scores[0])
            re_95ci=np.insert(re_95ci,0,pllm_95ci[0])
    fig,ax=plt.subplots(figsize=(6.4,3.5),layout='tight')
    offset=0.1
    b_trans=Affine2D().translate(-1*offset,0.0)+ax.transData
    r_trans=Affine2D().translate(offset,0.0)+ax.transData
    if base_perf_path:
        ax.errorbar(base_idx,base_scores,base_95ci,label=f'No patching',color='red',linestyle='dashed',transform=b_trans,linewidth=3)
    if portllm_perf_path:
        ax.errorbar(pllm_idx,pllm_scores,pllm_95ci,label=f'PortLLM patching',color='blue',linestyle='solid',linewidth=3)
    if recurrent_ft_perf_path:
        ax.errorbar(re_idx,re_scores,re_95ci,label=f'Stepwise fine-tuning',color='green',linestyle='dotted',transform=r_trans,linewidth=3)
    if add_arrow:
        ax.annotate("",xy=(base_idx[-1],base_scores[-1]),
                    xytext=(base_idx[-1],pllm_scores[-1]),
                    ha='center',va='center',
                    arrowprops={"arrowstyle":"<|-|>,head_width=0.5,head_length=1.5","color":"black"})
        ax.text(x=base_idx[-1]-2,y=(pllm_scores[-1]-base_scores[-1])/2+base_scores[-1],
                s=str(round(pllm_scores[-1] - base_scores[-1],2)),
                fontsize=24)
    plt.xlabel('Time step, $t$',fontsize=fs)
    plt.tick_params('both',labelsize=24)
    minacc=min([np.min(base_scores),np.min(pllm_scores),np.min(re_scores)])
    maxacc=max([np.max(base_scores),np.max(pllm_scores),np.max(re_scores)])
    ax.set_yticks([round(n,2) for n in np.arange(minacc,maxacc,(maxacc-minacc)/4)])
    ax.set_xticks([0,np.max(base_idx)//2, np.max(base_idx)])
    try:
        plt.savefig(f"plots/{benchmark}_{pt_set}{postfix}.pdf")
    except FileNotFoundError:
        os.mkdir(r'plots')
        plt.savefig(f"plots/{benchmark}_{pt_set}_avg_{str(rep)}{postfix}.pdf")
    plt.close()
    if gen_legend:
        lgd_fig=plt.figure(figsize=(2,1.5),layout='constrained')
        h,l=ax.get_legend_handles_labels()
        lgd_fig.legend(h,l,fontsize=fs)
        plt.subplots_adjust(left=0.2)
        try:
            plt.savefig(f"plots/legend.pdf",bbox_inches='tight',format='pdf')
        except FileNotFoundError:
            os.mkdir(r'plots')
            plt.savefig(f"plots/legend.pdf",bbox_inches='tight',format='pdf')
        
# first, Mistral pretrained on Fineweb
rep_folders=[f'temporal_evals/rep_{rep}_fw' for rep in range(1,4)]
base_fs=[f'{rep_f}/base' for rep_f in rep_folders]
pllm_fs=[f'{rep_f}/portllm' for rep_f in rep_folders]
re_fs=[f'{rep_f}/recurrent' for rep_f in rep_folders]

fs=30
for benchmark in ['winogrande','boolq','arc_easy','arc_challenge']: # main text benchmarks
    plot_scores_avg(benchmark,'fineweb',base_fs,pllm_fs,re_fs,[1,2,3],gen_legend=True,add_arrow=True)

for benchmark in ['mnli','sst2','gsm8k']: # additional benchmarks
    plot_scores_avg(benchmark,'fineweb',base_fs,pllm_fs,re_fs,[1,2,3],gen_legend=True)

# Mistral pretrained on Cosmopedia
rep_folders=[f'temporal_evals/rep_{rep}_cos' for rep in range(1,4)]
base_fs=[f'{rep_f}/base' for rep_f in rep_folders]
pllm_fs=[f'{rep_f}/portllm' for rep_f in rep_folders]
re_fs=[f'{rep_f}/recurrent' for rep_f in rep_folders]

for benchmark in ['winogrande','boolq','arc_easy','arc_challenge']:
    plot_scores_avg(benchmark,'cosmopedia',base_fs,pllm_fs,re_fs,[1,2,3])

# Qwen pretrained on Fineweb
rep_folders=[f'temporal_evals/rep_{rep}_qwen' for rep in range(1,4)]
base_fs=[f'{rep_f}/base' for rep_f in rep_folders]
pllm_fs=[f'{rep_f}/portllm' for rep_f in rep_folders]
re_fs=[f'{rep_f}/recurrent' for rep_f in rep_folders]

for benchmark in ['winogrande','boolq','arc_easy','arc_challenge']:
    plot_scores_avg(benchmark,'fineweb',base_fs,pllm_fs,re_fs,[1,2,3],postfix="_qwen")

# Gemma pretrained on Fineweb
rep_folders=[f'temporal_evals/rep_{rep}_gem' for rep in range(1,4)]
base_fs=[f'{rep_f}/base' for rep_f in rep_folders]
pllm_fs=[f'{rep_f}/portllm' for rep_f in rep_folders]
re_fs=[f'{rep_f}/recurrent' for rep_f in rep_folders]

for benchmark in ['winogrande','boolq','arc_easy','arc_challenge']:
    plot_scores_avg(benchmark,'fineweb',base_fs,pllm_fs,re_fs,[1,2,3],postfix="_gem")